server:
  port: 8090

spring:
  application:
    name: cryptography

  cloud:
    config:
      import-check:
        enabled: false

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
